apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    app: demo-voting-app

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres
    app: demo-voting-app

---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: vote-app
    app: demo-voting-app

---
apiVersion: v1
kind: Service
metadata:
  name: voteresult-app
  labels:
    name: voteresult-app
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 80
      nodePort: 30005
  selector:
    name: voteresult-app
    app: demo-voting-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: redis
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        name: redis
        app: demo-voting-app
    spec:
      containers:
        - name: redis
          image: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: postgres
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteresult-app
  labels:
    tier: front-end
spec:
  selector:
    matchLabels:
      name: voteresult-app
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: voteresult-app
      labels:
        name: voteresult-app
        app: demo-voting-app
    spec:
      containers:
        - name: vote-app
          image: kodekloud/examplevotingapp_result:v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    tier: front-end
spec:
  selector:
    matchLabels:
      name: vote-app
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: vote-app
      labels:
        name: vote-app
        app: demo-voting-app
    spec:
      containers:
        - name: vote-app
          image: kodekloud/examplevotingapp_vote:v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    tier: back-end
spec:
  selector:
    matchLabels:
      name: worker-app
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: worker-app
      labels:
        name: worker-app
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
